name: Deploy React Application

on:
  push:
    branches: [ main ]
      #  pull_request:
      #    branches: [ main ]

jobs:
  build_site:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # We will deploy with only one version of node  

    permissions:
      contents: write
      pages: write

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: build site
        run: |
          npm install
          npm install gh-pages --save-dev
      - name: deploy to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EMAIL: perfscale-automation@redhat.com
          GH_USERNAME: redhat-perfbot
        run: |
          git config --global user.name $GH_USERNAME
          git config --global user.email $GH_EMAIL
          git remote set-url origin https://$GH_USERNAME:$GITHUB_TOKEN@github.com/redhat-performance/tooling-curator.git
          npm run deploy
